<!DOCTYPE html>
<html>
<head>
    <title>Title of the document</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link href='http://fonts.googleapis.com/css?family=Ubuntu|Kalam' rel='stylesheet' type='text/css'>
    <link href='styles/style.css' rel='stylesheet' type='text/css'>
</head>
<body>
<div>
    <div id="loginbox"><a href="php/logout.php" id="loginbox">logout</a></div>
    <div id="headline">St. LAN 2.0</div>
<!-- page content starts here... -->